"""Synthetic, self-contained inputs for Golden acceptance.

Golden verifies the deterministic pipeline contract.  It must never require
personal PDFs from ``input/``.  This module materializes only blank PDFs with
the canonical filenames/page counts, plus the checked-in page-signal fixtures
and a deterministic agent-analysis fixture derived from the Golden contract.
"""
from __future__ import annotations

import json
import hashlib
import shutil
import tempfile
from contextlib import contextmanager
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from typing import Iterator

from pypdf import PdfWriter

from .models import PipelineError

GOLDEN_DIR = "test_cases"
VISION_FIXTURE_DIR = Path("fixtures") / "vision"
ANALYSIS_DIR = "analysis"
PDF_PAGE_SIZE = (612, 792)  # US Letter points; fixed so generated bytes are stable.


@dataclass(frozen=True)
class GoldenFixtureWorkspace:
    """Paths containing test-only assets for one isolated Golden invocation."""

    root: Path
    person_folder: Path
    fixture_root: Path
    analysis_root: Path
    source_sha256: dict[str, str]


def load_golden_contracts(repo_root: Path) -> list[tuple[Path, dict]]:
    """Load every checked-in Golden contract, rejecting malformed source declarations."""
    root = Path(repo_root)
    paths = sorted((root / GOLDEN_DIR).glob("*.json"))
    if not paths:
        raise PipelineError(f"Không có file golden nào trong {root / GOLDEN_DIR}")
    contracts: list[tuple[Path, dict]] = []
    for path in paths:
        raw = json.loads(path.read_text(encoding="utf-8"))
        cases = raw.get("cases") or []
        if not cases:
            raise PipelineError(f"Golden {path.name} không có cases.")
        for case in cases:
            name = case.get("source_file")
            pages = case.get("source_pages")
            if not isinstance(name, str) or not name or Path(name).name != name:
                raise PipelineError(f"Golden {path.name}: source_file không hợp lệ: {name!r}")
            if not isinstance(pages, int) or isinstance(pages, bool) or pages < 1:
                raise PipelineError(
                    f"Golden {path.name}: source_pages của {name!r} phải là số nguyên >= 1."
                )
        contracts.append((path, raw))
    return contracts


def deterministic_blank_pdf(page_count: int) -> bytes:
    """Return a valid blank PDF with a fixed page count and stable metadata."""
    if not isinstance(page_count, int) or isinstance(page_count, bool) or page_count < 1:
        raise ValueError("page_count phải là số nguyên >= 1")
    writer = PdfWriter()
    writer.add_metadata({"/Producer": "party-record-golden-fixture", "/CreationDate": "D:20000101000000Z"})
    for _ in range(page_count):
        writer.add_blank_page(width=PDF_PAGE_SIZE[0], height=PDF_PAGE_SIZE[1])
    payload = BytesIO()
    writer.write(payload)
    return payload.getvalue()


def stage_golden_workspace(repo_root: Path, destination: Path) -> GoldenFixtureWorkspace:
    """Materialize all Golden assets in ``destination`` without reading ``input/``.

    The destination must be empty or absent.  It receives only test contract,
    blank synthetic PDFs, and checked-in fixture JSON.  No runtime output,
    review, logs, or state data are copied or created.
    """
    repo_root = Path(repo_root)
    destination = Path(destination)
    if destination.exists() and any(destination.iterdir()):
        raise PipelineError(f"Golden fixture destination phải rỗng: {destination}")
    destination.mkdir(parents=True, exist_ok=True)

    contracts = load_golden_contracts(repo_root)
    contract_dir = destination / GOLDEN_DIR
    contract_dir.mkdir()
    for path, _ in contracts:
        shutil.copy2(path, contract_dir / path.name)

    sources: dict[str, tuple[str, int]] = {}
    for _, golden in contracts:
        person = _golden_person_folder(golden)
        for case in golden["cases"]:
            name = case["source_file"]
            pages = case["source_pages"]
            previous = sources.get(name)
            if previous is not None and previous != (person, pages):
                raise PipelineError(f"Golden khai báo mâu thuẫn cho source {name!r}.")
            sources[name] = (person, pages)

    persons = {person for person, _ in sources.values()}
    if len(persons) != 1:
        raise PipelineError("Golden fixture hiện chỉ hỗ trợ một person_folder mỗi lần chạy.")
    person = next(iter(persons))
    input_folder = destination / "input" / person
    input_folder.mkdir(parents=True)
    source_hashes: dict[str, str] = {}
    for name, (_, pages) in sorted(sources.items()):
        content = deterministic_blank_pdf(pages)
        target = input_folder / name
        target.write_bytes(content)
        source_hashes[name] = hashlib.sha256(content).hexdigest()

    fixture_root = destination / VISION_FIXTURE_DIR
    source_fixture_dir = repo_root / VISION_FIXTURE_DIR / person
    if not source_fixture_dir.is_dir():
        raise PipelineError(f"Thiếu page-signal fixture Golden: {source_fixture_dir}")
    shutil.copytree(source_fixture_dir, fixture_root / person)

    analysis_root = destination / ANALYSIS_DIR
    _stage_agent_analysis(contracts, fixture_root, analysis_root, person)
    return GoldenFixtureWorkspace(
        root=destination,
        person_folder=input_folder,
        fixture_root=fixture_root,
        analysis_root=analysis_root,
        source_sha256=source_hashes,
    )


@contextmanager
def isolated_golden_workspace(repo_root: Path, *, temp_parent: Path | None = None) -> Iterator[GoldenFixtureWorkspace]:
    """Create and clean up a Golden-only workspace, optionally under a test parent."""
    parent = str(Path(temp_parent)) if temp_parent is not None else None
    with tempfile.TemporaryDirectory(prefix="party-record-golden-", dir=parent) as raw:
        yield stage_golden_workspace(repo_root, Path(raw))


def _golden_person_folder(golden: dict) -> str:
    person = golden.get("person_folder") or "SYNTHETIC_GOLDEN"
    if not isinstance(person, str) or not person or Path(person).name != person:
        raise PipelineError(f"Golden person_folder không hợp lệ: {person!r}")
    return person


def _stage_agent_analysis(
    contracts: list[tuple[Path, dict]], fixture_root: Path, analysis_root: Path, person: str
) -> None:
    """Build an offline agent fixture from page signals plus Golden expectations."""
    target_dir = analysis_root / person
    target_dir.mkdir(parents=True)
    for _, golden in contracts:
        if _golden_person_folder(golden) != person:
            continue
        for case in golden["cases"]:
            source_file = case["source_file"]
            fixture_path = fixture_root / person / (Path(source_file).stem + ".json")
            if not fixture_path.is_file():
                raise PipelineError(f"Thiếu fixture cho Golden source {source_file!r}: {fixture_path}")
            page_signals = json.loads(fixture_path.read_text(encoding="utf-8"))
            expected_docs = case.get("expected_documents") or []
            analysis = {
                "schema_version": "1.0",
                "produced_by": "golden-synthetic-fixture",
                "person_folder": person,
                "source_file": source_file,
                "page_count": case["source_pages"],
                "pages": page_signals.get("pages") or [],
                "documents": [
                    {
                        "source_pages": doc["pages"],
                        "type_id": doc["type_id"],
                        "confidence": 0.97,
                        "document_date": doc.get("document_date"),
                        "date_confidence": 0.97 if doc.get("document_date") else 0.0,
                        "title_short": doc.get("title_short"),
                        "needs_review": bool(doc.get("expected_review", False)),
                        "review_reason": "golden fixture expected review" if doc.get("expected_review") else None,
                    }
                    for doc in expected_docs
                ],
            }
            target = target_dir / (Path(source_file).stem + ".json")
            target.write_text(json.dumps(analysis, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
